import argparse
import os.path
import re
from typing import List

def split_on_capitals(text: str) -> List[str]:
  return re.findall("[A-Z][^A-Z]*", text)


def app():
  parser = argparse.ArgumentParser("Measurement Set v4 utilities")
  parser.add_argument("command", choices=["generate-types"])
  parsed_args = parser.parse_args()

  if parsed_args.command == "generate-types":
    try:
      import xradio.measurement_set.schema as ms_schema
    except ImportError as e:
      raise ImportError("Install the latest version of xradio") from e

    type_to_dataset_map = {}

    # Scan the schema module for dataset schemas
    for name in dir(ms_schema):
      attr = getattr(ms_schema, name)

      if model := getattr(attr, "__xradio_dataset_schema", False):
        try:
          type_schema = next(iter(a for a in model.attributes if a.name == "type"))
        except StopIteration:
          continue
        else:
          single_type = len(type_schema.literal) <= 1

          # Generate an appropriate name for the Dataset
          var_name_bits = [n.upper() for n in split_on_capitals(name)]
          var_name_bits.extend(["TYPE" if single_type else "TYPES"])
          var_name = "_".join(var_name_bits)
          type_to_dataset_map[var_name] = type_schema.literal[0] if single_type else tuple(type_schema.literal)

    # Write out the type(s) for each dataset variant
    type_filename = os.path.join(os.path.split(__file__)[0], "msv4_types.py")

    with open(type_filename, mode="w") as f:
      f.write(f"# Auto-generated by \"msv4-utils {parsed_args.command}\"\n\n")

      for k, v in type_to_dataset_map.items():
        value = f"{v}".replace("'", "\"") if isinstance(v, tuple) else f"\"{v}\""
        f.write(f"{k} = {value}\n")
