# Auto-generated by "msv4-utils generate-types"

ANTENNA_XDS_TYPE = "antenna"
FIELD_SOURCE_EPHEMERIS_XDS_TYPE = "field_and_source_ephemeris"
FIELD_SOURCE_XDS_TYPE = "field_and_source"
GAIN_CURVE_XDS_TYPE = "gain_curve"
PHASE_CALIBRATION_XDS_TYPE = "phase_calibration"
PHASED_ARRAY_XDS_TYPE = "phased_array"
POINTING_XDS_TYPE = "pointing"
SPECTRUM_XDS_TYPE = "spectrum"
SYSTEM_CALIBRATION_XDS_TYPE = "system_calibration"
VISIBILITY_XDS_TYPES = ("visibility", "radiometer")
WEATHER_XDS_TYPE = "weather"
